apiVersion: v1     
kind: Service         # 表明是 kubernetes service
metadata:         
  name: mysql         # service的全局唯一名称
spec:
  ports:
  - port: 3306        # service 提供服务的端口号
  selector:           # service 对应的Pod拥有这里定义的标签
    app: mysql