apiVersion: v1
kind: Pod
metadata:
    name: pod-tolerations
spec:
    containers:
    -   name: pod-tolerations
        image: nginx
    tolerations:
    -   key: "key"
        operator: "Equal"
        value: "value"
        effect: "NoSchedule"
    #或者使用一下形式
    tolerations:
    -   key: "key"
        operator: "Exists"
        effect: "NoSchedule"